# Site settings
name: "Kisuc Kim"
description: "Welcome to my Github Page"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  kimks0818
facebook_username: kimks0818
linkedin_username: kimks0818
blog_url: www.kisuckim.com
email: kimks0818@gmail.com


avatar: yes
#avatar_img_path: "https://media.licdn.com/dms/image/C5103AQHxYeIxJ6xNAw/profile-displayphoto-shrink_200_200/0?e=1561593600&v=beta&t=hef2Jh8SW-1nMBf3B1aBAd8UxzzTSZcl3Np2abgmggo"
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://media.licdn.com/dms/image/C5103AQHxYeIxJ6xNAw/profile-displayphoto-shrink_200_200/0?e=1561593600&v=beta&t=hef2Jh8SW-1nMBf3B1aBAd8UxzzTSZcl3Np2abgmggo"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
